
import 'package:elpian_ui/elpian_ui.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

/// The CLI's `showcase` template, running as bytecode.
///
/// The program is not written here — it is generated by
/// `elpian create --template showcase`, compiled to `.elpian.bc`, and bundled as
/// an asset by `.github/workflows/build_showcase.yml`. So this screen runs the
/// very program the template produces: if the template drifts from the runtime,
/// this breaks rather than quietly diverging.
///
/// The program emits a `Scene3D` stage surrounded by a 2D GUI; both come out of
/// the same `render()` call.
class ShowcaseExample extends StatefulWidget {
  const ShowcaseExample({super.key});

  @override
  State<ShowcaseExample> createState() => _ShowcaseExampleState();
}

class _ShowcaseExampleState extends State<ShowcaseExample> {
  late final Future<Uint8List?> _bytecode = _load();

  /// Returns null when the asset is absent — a plain checkout has no compiled
  /// showcase, and that must show an explanation rather than a crash.
  Future<Uint8List?> _load() async {
    try {
      final data = await rootBundle.load('assets/showcase/client.elpian.bc');
      return data.buffer.asUint8List();
    } catch (_) {
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0B0F16),
      body: SafeArea(
        child: FutureBuilder<Uint8List?>(
          future: _bytecode,
          builder: (context, snapshot) {
            if (snapshot.connectionState != ConnectionState.done) {
              return const Center(child: CircularProgressIndicator());
            }
            final bytes = snapshot.data;
            if (bytes == null) return const _MissingShowcase();
            return ElpianVmWidget.fromBytecode(
              machineId: 'elpian-showcase',
              bytecode: bytes,
              onPrintln: (m) => debugPrint('[showcase] $m'),
              errorBuilder: (error) => Center(
                child: Padding(
                  padding: const EdgeInsets.all(24),
                  child: SelectableText(
                    error,
                    style: const TextStyle(color: Colors.orangeAccent),
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

class _MissingShowcase extends StatelessWidget {
  const _MissingShowcase();

  @override
  Widget build(BuildContext context) => const Center(
        child: Padding(
          padding: EdgeInsets.all(32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.inventory_2_outlined, size: 40, color: Colors.white24),
              SizedBox(height: 12),
              Text(
                'No compiled showcase bundled.\n\n'
                'Generate and build it:\n'
                '  elpian create showcase-app --template showcase\n'
                '  cd showcase-app && elpian run install && elpian run build\n'
                '  cp dist/client.elpian.bc ../example/assets/showcase/',
                textAlign: TextAlign.center,
                style: TextStyle(color: Colors.white38, fontSize: 12, height: 1.6),
              ),
            ],
          ),
        ),
      );
}
